# Generated by Django 4.2.4 on 2023-08-22 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marksmodel',
            name='student',
        ),
        migrations.AddField(
            model_name='marksmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
